// https://gradle.com
plugins {
    id "com.gradle.enterprise" version "3.10.3"
}

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com"
        termsOfServiceAgree = "yes"
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral() // Busca el artefacto directamente en los repositorios de Sonatype/Central
    }
}

rootProject.name = "METROX"
include ':app', ':appthemehelper'
