// https://docs.gradle.com/enterprise/gradle-plugin/
plugins {
    id "com.gradle.enterprise" version "3.10.3"
}

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}

dependencyResolutionManagement {
    // FAIL_ON_PROJECT_REPOS asegura que todos los módulos usen esta configuración centralizada
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        // Se eliminó el bloque flatDir porque ya no buscaremos librerías .aar en carpetas locales.
    }
}

rootProject.name = "METROX"
include ':app', ':appthemehelper'
